# Generated by Django 5.0.7 on 2025-01-21 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('Profile_Picture', models.ImageField(upload_to='admin_profile/')),
                ('Phone_Number', models.CharField(max_length=11)),
                ('State_Of_Origin', models.CharField(max_length=50)),
                ('Local_Government', models.CharField(max_length=50)),
                ('Country_Of_Origin', models.CharField(max_length=50)),
                ('Town_Of_Origin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField(max_length=5)),
                ('Profile_Picture', models.ImageField(upload_to='student_profile/')),
                ('Student_Class', models.CharField(max_length=10)),
                ('Student_Email', models.EmailField(max_length=254)),
                ('Guardian_Name', models.CharField(max_length=50)),
                ('Guardian_phone_Number', models.CharField(max_length=11)),
                ('Guardian_Address', models.CharField(max_length=50)),
                ('State_Of_Origin', models.CharField(max_length=50)),
                ('Local_Government', models.CharField(max_length=50)),
                ('Country_Of_Origin', models.CharField(max_length=50)),
                ('Town_Of_Origin', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Post_In_School', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Health_Issues', models.TextField()),
                ('Registration_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('Profile_Picture', models.ImageField(upload_to='teacher_profile/')),
                ('Subject', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Age', models.IntegerField(max_length=15)),
                ('Next_Of_Kin', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=11)),
                ('State_Of_Origin', models.CharField(max_length=50)),
                ('Local_Government', models.CharField(max_length=50)),
                ('Country_Of_Origin', models.CharField(max_length=50)),
                ('Town_Of_Origin', models.CharField(max_length=50)),
                ('Registration_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
