# Generated by Django 5.0.7 on 2025-02-05 15:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Age', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('Profile_Picture', models.ImageField(upload_to='student_profile/')),
                ('grade', models.CharField(default=1, max_length=50)),
                ('Guardian_Name', models.CharField(max_length=100)),
                ('Guardian_phone_Number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', message='Enter a valid phone number.')])),
                ('Guardian_Address', models.CharField(max_length=255)),
                ('State_Of_Origin', models.CharField(max_length=50)),
                ('Local_Government', models.CharField(max_length=50)),
                ('Country_Of_Origin', models.CharField(max_length=50)),
                ('Town_Of_Origin', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('Health_Issues', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SMS_APP.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_Title', models.CharField(max_length=100)),
                ('News_Image', models.ImageField(upload_to='news_image/')),
                ('News_Body', models.TextField()),
                ('Comment', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMS_APP.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Profile_Picture', models.ImageField(upload_to='teacher_profile/')),
                ('subject_specialization', models.CharField(max_length=100, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('Age', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(18)])),
                ('Next_Of_Kin', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', message='Enter a valid phone number.')])),
                ('State_Of_Origin', models.CharField(max_length=50)),
                ('Local_Government', models.CharField(max_length=50)),
                ('Country_Of_Origin', models.CharField(max_length=50)),
                ('Town_Of_Origin', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('Health_Issues', models.TextField(blank=True, null=True)),
                ('identification_type', models.CharField(choices=[('NID', 'National ID'), ('PASS', 'Passport'), ('DL', 'Driver’s License'), ('VOTER', 'Voter’s Card'), ('OTH', 'Other')], default='NID', max_length=10, verbose_name='Identification Type')),
                ('identification_number', models.CharField(max_length=50, null=True, unique=True, verbose_name='ID Number')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SMS_APP.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Annoncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='announcement_image/')),
                ('Body', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Teacher_Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SMS_APP.teacher')),
            ],
        ),
    ]
