# Generated by Django 5.0.7 on 2025-01-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Annoncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='announcement_image/')),
                ('Body', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Admin_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS_APP.admin')),
                ('Teacher_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS_APP.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_Title', models.CharField(max_length=100)),
                ('News_Image', models.ImageField(upload_to='news_image/')),
                ('News_Body', models.TextField()),
                ('Comment', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS_APP.student')),
            ],
        ),
    ]
