# Generated by Django 5.1.5 on 2025-01-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SMS_APP", "0003_remove_news_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annoncement",
            name="Admin_Author",
        ),
        migrations.RemoveField(
            model_name="annoncement",
            name="Teacher_Author",
        ),
    ]
